name: typesense
services:
    nginx:
        hostname: nginx.docs.next
        image: nginx:1-alpine
        ports:
            - 80:80
        volumes:
            - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on:
            - typesense
        extra_hosts:
            - "host.docker.internal:host-gateway"
    typesense:
        ports:
            - 8108:8108
        volumes:
            - typesense_data:/data
        image: typesense/typesense:26.0
        command: --data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors=true
        hostname: typesense.docs.next
        healthcheck: 
            test: ['CMD', 'curl', 'http://localhost:8108']
            interval: 5s
            timeout: 3s
            retries: 5
        extra_hosts:
            - "host.docker.internal:host-gateway"
    docsearch-scraper:
        hostname: scraper.docs.next
        restart: on-failure:5
        environment:
            - CONFIG=${CONFIG_JSON}
            - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
            - TYPESENSE_HOST=typesense.docs.next
            - TYPESENSE_PORT=8108
            - TYPESENSE_PROTOCOL=http
        image: typesense/docsearch-scraper:0.9.1
        depends_on:
            - nginx
        extra_hosts:
            - "host.docker.internal:host-gateway"
volumes:
    typesense_data:
        external: true
        name: typesense_data