on:
    push:
      branches:
        - create-build-workflow 
    pull_request:
      branches: 
        - main
jobs:
    build:
      environment: preview
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18 # Use Node.js 18 here
  
        - name: Install dependencies
          run: npm install
  
        - name: Build site
          env: 
            TYPESENSE_PROTOCOL: ${{ vars.TYPESENSE_PROTOCOL }}
            TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
            TYPESENSE_PORT: ${{ vars.TYPESENSE_PORT }}
            TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
          run: npm run build

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1 
          
        - name: Build and push 
          id: docker_build 
          uses: docker/build-push-action@v2
          with: 
            context: ./
            file: ./Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:${GITHUB_SHA::6}
        
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

        # - name: Build and push
        #   uses: docker/build-push-action@v5
        #   with:
        #     push: true
        #     tags: akyriako78/docs-next-preview:0.0.1
        
      