on:
    push:
      branches:
        - create-build-workflow 
    pull_request:
      branches: 
        - main
jobs:
    build:
      environment: preview
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v2
  
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: 18 # Use Node.js 18 here
  
        - name: Install Dependencies
          run: npm install
  
        - name: Build App
          env: 
            TYPESENSE_PROTOCOL: ${{ vars.TYPESENSE_PROTOCOL }}
            TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
            TYPESENSE_PORT: ${{ vars.TYPESENSE_PORT }}
            TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
          run: npm run build

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        - name: Setup Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1 
        
        - name: Get Commit Hash
          id: commit_hash
          uses: prompt/actions-commit-hash@v3
        - uses: docker/setup-buildx-action@v3
        - name: Build and Push (Docker Image)
          id: docker_build 
          uses: docker/build-push-action@v2
          with: 
            context: ./
            file: ./Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:${{ steps.commit_hash.outputs.short }}
        
        # - name: Image Digest
        #   run: echo ${{ steps.docker_build.outputs.digest }}

    update-tag:
      needs: build
      environment: preview
      runs-on: ubuntu-latest
      steps:
        - name: Get Commit Hash
          id: commit_hash
          uses: prompt/actions-commit-hash@v3
        - name: Show Commit Hash Digest
          run: echo ${{ steps.commit_hash.outputs.short }}
        - name: Update Image Tag
          uses: cheelim1/image-updater@v1.11
          with:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            REPO_NAME: 'docs-next-charts'
            REPO_OWNER: 'akyriako'
            FILE_PATH: 'chart/templates/values.yaml'
            IMAGE_TAG:  ${{ steps.commit_hash.outputs.short }}


          
      