on:
    push:
      branches:
        - create-build-workflow # Change this to your default branch if it's different
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18 # Use Node.js 18 here
  
        - name: Install dependencies
          run: npm install
  
        - name: Build site
          run: npm run build
  