on:
    push:
      branches:
        - refine_workflow
    # pull_request:
    #   branches: 
    #     - main
jobs:
    build-app:
      environment: preview
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v2
  
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: 18 # Use Node.js 18 here
  
        - name: Install Dependencies
          run: npm install
  
        - name: Build App
          env: 
            TYPESENSE_PROTOCOL: ${{ vars.TYPESENSE_PROTOCOL }}
            TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
            TYPESENSE_PORT: ${{ vars.TYPESENSE_PORT }}
            TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
          run: npm run build

    build-push-docker:
      environment: preview
      runs-on: ubuntu-latest
      needs: build-app

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        - name: Setup Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1 
        
        - name: Get Commit Hash
          id: commit_hash
          uses: prompt/actions-commit-hash@v3
        - uses: docker/setup-buildx-action@v3
        - name: Build and Push (Docker Image)
          id: docker_build 
          uses: docker/build-push-action@v2
          with: 
            context: ./
            file: ./Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:${{ steps.commit_hash.outputs.short }}
        
        # - name: Image Digest
        #   run: echo ${{ steps.docker_build.outputs.digest }}

    update-helm-charts:
      needs: [build-app, build-push-docker]
      environment: preview
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with: 
            repository: 'akyriako/docs-next-charts'

        - name: Show Contents
          run: ls -latr

        - name: Get Commit Hash
          id: commit_hash
          uses: prompt/actions-commit-hash@v3

        - name: Show Commit Hash Digest
          run: echo ${{ steps.commit_hash.outputs.short }}

        - name: Set GitHub Actions Bot Credentials
          id: set_bot_creds
          uses: rindeal/action-git-config-user@v1

        - name: Update Charts
          id: update_charts
          run: |
            sed -i 's/^version: .*/version: ${{ vars.APP_VERSION }}.${{github.run_id}}/' ./charts/docusaurus/Chart.yaml
            sed -i 's/^appVersion: .*/appVersion: ${{ vars.APP_VERSION }}.${{github.run_id}}-${{ steps.commit_hash.outputs.short }}/' ./charts/docusaurus/Chart.yaml
            sed -i 's/^imageTag: .*/imageTag: ${{ steps.commit_hash.outputs.short }}/' ./charts/docusaurus/values.yaml
            sed -i 's/^version: .*/version: ${{ vars.APP_VERSION }}.${{github.run_id}}/' ./charts/typesense/Chart.yaml
            sed -i 's/^appVersion: .*/appVersion: ${{ vars.APP_VERSION }}.${{github.run_id}}-${{ steps.commit_hash.outputs.short }}/' ./charts/typesense/Chart.yaml
            git commit -am "Automatic commit from GitHub Actions triggered by action #${{github.run_id}}"
            git push origin main 


      

          
      